server:
  port: 2003


spring:
  application:
    name: seata-account-service
  cloud:
    alibaba:
      seata:
          #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    nacos:
      discovery:
        server-addr: localhost:8848
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata_account?characterEncoding=utf8&connectTimeout=1000&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: jimiwenjian



logging:
  level:
    io:
      seata: info


mybatis:
  mapper-locations: classpath:mapper/*.xml